#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kexec-tools
Version  : 2.0.15
Release  : 7
URL      : https://www.kernel.org/pub/linux/utils/kernel/kexec/kexec-tools-2.0.15.tar.xz
Source0  : https://www.kernel.org/pub/linux/utils/kernel/kexec/kexec-tools-2.0.15.tar.xz
Summary  : Load one kernel from another
Group    : Development/Tools
License  : GPL-2.0
Requires: kexec-tools-bin
Requires: kexec-tools-doc
BuildRequires : pkgconfig(zlib)
BuildRequires : xz-dev

%description
/sbin/kexec is a user space utility for loading another kernel
and asking the currently running kernel to do something with it.
A currently running kernel may be asked to start the loaded
kernel on reboot, or to start the loaded kernel after it panics.

The panic case is useful for having an intact kernel for writing
crash dumps.  But other uses may be imagined.

%package bin
Summary: bin components for the kexec-tools package.
Group: Binaries

%description bin
bin components for the kexec-tools package.


%package doc
Summary: doc components for the kexec-tools package.
Group: Documentation

%description doc
doc components for the kexec-tools package.


%prep
%setup -q -n kexec-tools-2.0.15

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1497688328
%configure --disable-static
make V=1  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1497688328
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib64/kexec-tools/kexec_test

%files bin
%defattr(-,root,root,-)
/usr/bin/kdump
/usr/bin/kexec
/usr/bin/vmcore-dmesg

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man8/*
